# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='chac',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='characters',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='chti',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='containers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='drinks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='enemies',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='friends',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fullst',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scenarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ticks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tools',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='weapons',
            options={'managed': True},
        ),
    ]
